import * as actionTypes from '../Constants';

const initialState = {
  Players: [
    {
      name: 'Cristiano Ronaldo',
      nameAbb: 'C. Ronaldo',
      defSkill: 4,
      midSkill: 7,
      atkSkill: 10,
      teamless: true,
    },
    {
      name: 'Richard Papillon',
      nameAbb: 'Shox',
      defSkill: 5,
      midSkill: 9,
      atkSkill: 7,
      teamless: true,
    },
    {
      name: 'Augustas Eidikis',
      nameAbb: 'A. Eidikis',
      defSkill: 3,
      midSkill: 8,
      atkSkill: 9,
      teamless: true,
    },
    {
      name: 'Luka Perković',
      nameAbb: 'Perkz',
      defSkill: 6,
      midSkill: 6,
      atkSkill: 8,
      teamless: true,
    },
    {
      name: 'Oleksandr Kostyliev',
      nameAbb: 'S1mple',
      defSkill: 5,
      midSkill: 5,
      atkSkill: 10,
      teamless: true,
    },
    {
      name: 'Ilya Zalutskiy',
      nameAbb: 'Perfecto',
      defSkill: 8,
      midSkill: 6,
      atkSkill: 4,
      teamless: true,
    },
    {
      name: 'Nikola Kovač',
      nameAbb: 'NiKo',
      defSkill: 5,
      midSkill: 7,
      atkSkill: 7,
      teamless: true,
    },
    {
      name: 'Ludvig Brolin',
      nameAbb: 'Brollan',
      defSkill: 2,
      midSkill: 6,
      atkSkill: 9,
      teamless: true,
    },
    {
      name: 'Henrik Hansen',
      nameAbb: 'Froggen',
      defSkill: 5,
      midSkill: 8,
      atkSkill: 5,
      teamless: true,
    },
    {
      name: 'Barney Morris',
      nameAbb: 'Alphari',
      defSkill: 4,
      midSkill: 9,
      atkSkill: 3,
      teamless: true,
    },
    {
      name: 'Robert Lewandowski',
      nameAbb: 'R. Lewandowski',
      defSkill: 2,
      midSkill: 7,
      atkSkill: 8,
      teamless: true,
    },
    {
      name: 'Francesco Totti',
      nameAbb: 'F. Totti',
      defSkill: 3,
      midSkill: 10,
      atkSkill: 5,
      teamless: true,
    },
    {
      name: 'Paolo Maldini',
      nameAbb: 'P. Maldini',
      defSkill: 9,
      midSkill: 7,
      atkSkill: 2,
      teamless: true,
    },
    {
      name: 'Nemanja Vidić',
      nameAbb: 'N. Vidić',
      defSkill: 10,
      midSkill: 5,
      atkSkill: 1,
      teamless: true,
    },
    {
      name: 'Oskar Bogdan',
      nameAbb: 'Vander',
      defSkill: 8,
      midSkill: 3,
      atkSkill: 3,
      teamless: true,
    },
    {
      name: 'Andrei Pascu',
      nameAbb: 'Odoamne',
      defSkill: 6,
      midSkill: 6,
      atkSkill: 4,
      teamless: true,
    },
    {
      name: 'Rasmus Winther',
      nameAbb: 'CaPs',
      defSkill: 3,
      midSkill: 7,
      atkSkill: 9,
      teamless: true,
    },
    {
      name: 'Rekkles',
      nameAbb: 'Brollan',
      defSkill: 2,
      midSkill: 6,
      atkSkill: 9,
      teamless: true,
    },
    {
      name: 'Jankos',
      nameAbb: 'Froggen',
      defSkill: 5,
      midSkill: 8,
      atkSkill: 5,
      teamless: true,
    },
    {
      name: 'Upset',
      nameAbb: 'Alphari',
      defSkill: 4,
      midSkill: 9,
      atkSkill: 3,
      teamless: true,
    },
    {
      name: 'Benzema',
      nameAbb: 'C. Ronaldo',
      defSkill: 4,
      midSkill: 7,
      atkSkill: 10,
      teamless: true,
    },
    {
      name: 'Modric',
      nameAbb: 'Shox',
      defSkill: 5,
      midSkill: 9,
      atkSkill: 7,
      teamless: true,
    },
    {
      name: 'Griezmann',
      nameAbb: 'A. Eidikis',
      defSkill: 3,
      midSkill: 8,
      atkSkill: 9,
      teamless: true,
    },
    {
      name: 'Muller',
      nameAbb: 'Perkz',
      defSkill: 6,
      midSkill: 6,
      atkSkill: 8,
      teamless: true,
    },
    {
      name: 'Pavard',
      nameAbb: 'S1mple',
      defSkill: 5,
      midSkill: 5,
      atkSkill: 10,
      teamless: true,
    },
    {
      name: 'Rashford',
      nameAbb: 'Perfecto',
      defSkill: 8,
      midSkill: 6,
      atkSkill: 4,
      teamless: true,
    },
    {
      name: 'Hålaand',
      nameAbb: 'NiKo',
      defSkill: 5,
      midSkill: 7,
      atkSkill: 7,
      teamless: true,
    },
    {
      name: 'Chellini',
      nameAbb: 'Brollan',
      defSkill: 2,
      midSkill: 6,
      atkSkill: 9,
      teamless: true,
    },
    {
      name: 'Kante',
      nameAbb: 'Froggen',
      defSkill: 5,
      midSkill: 8,
      atkSkill: 5,
      teamless: true,
    },
    {
      name: 'Grigonis',
      nameAbb: 'Alphari',
      defSkill: 4,
      midSkill: 9,
      atkSkill: 3,
      teamless: true,
    },
    {
      name: 'Sabonis',
      nameAbb: 'C. Ronaldo',
      defSkill: 4,
      midSkill: 7,
      atkSkill: 10,
      teamless: true,
    },
    {
      name: 'Lukaku',
      nameAbb: 'Shox',
      defSkill: 5,
      midSkill: 9,
      atkSkill: 7,
      teamless: true,
    },
    {
      name: 'Hazard',
      nameAbb: 'A. Eidikis',
      defSkill: 3,
      midSkill: 8,
      atkSkill: 9,
      teamless: true,
    },
    {
      name: 'Xhaka',
      nameAbb: 'Perkz',
      defSkill: 6,
      midSkill: 6,
      atkSkill: 8,
      teamless: true,
    },
    {
      name: 'Ramos',
      nameAbb: 'S1mple',
      defSkill: 5,
      midSkill: 5,
      atkSkill: 10,
      teamless: true,
    },
    {
      name: 'Kane',
      nameAbb: 'Perfecto',
      defSkill: 8,
      midSkill: 6,
      atkSkill: 4,
      teamless: true,
    },
    {
      name: 'De bruyne',
      nameAbb: 'NiKo',
      defSkill: 5,
      midSkill: 7,
      atkSkill: 7,
      teamless: true,
    },
    {
      name: 'Kajbjer',
      nameAbb: 'Brollan',
      defSkill: 2,
      midSkill: 6,
      atkSkill: 9,
      teamless: true,
    },
    {
      name: 'Hampus',
      nameAbb: 'Froggen',
      defSkill: 5,
      midSkill: 8,
      atkSkill: 5,
      teamless: true,
    },
    {
      name: 'Valanciunas',
      nameAbb: 'Alphari',
      defSkill: 4,
      midSkill: 9,
      atkSkill: 3,
      teamless: true,
    },
    {
      name: 'Van Persie',
      nameAbb: 'C. Ronaldo',
      defSkill: 4,
      midSkill: 7,
      atkSkill: 10,
      teamless: true,
    },
    {
      name: 'Company',
      nameAbb: 'Shox',
      defSkill: 5,
      midSkill: 9,
      atkSkill: 7,
      teamless: true,
    },
    {
      name: 'Jorginho',
      nameAbb: 'A. Eidikis',
      defSkill: 3,
      midSkill: 8,
      atkSkill: 9,
      teamless: true,
    },
    {
      name: 'Mbappe',
      nameAbb: 'Perkz',
      defSkill: 6,
      midSkill: 6,
      atkSkill: 8,
      teamless: true,
    },
    {
      name: 'Zywoo',
      nameAbb: 'S1mple',
      defSkill: 5,
      midSkill: 5,
      atkSkill: 10,
      teamless: true,
    },
    {
      name: 'Chiesa',
      nameAbb: 'Perfecto',
      defSkill: 8,
      midSkill: 6,
      atkSkill: 4,
      teamless: true,
    },
    {
      name: 'Immobile',
      nameAbb: 'NiKo',
      defSkill: 5,
      midSkill: 7,
      atkSkill: 7,
      teamless: true,
    },
    {
      name: 'KennyS',
      nameAbb: 'Brollan',
      defSkill: 2,
      midSkill: 6,
      atkSkill: 9,
      teamless: true,
    },
    {
      name: 'Gilius',
      nameAbb: 'Froggen',
      defSkill: 5,
      midSkill: 8,
      atkSkill: 5,
      teamless: true,
    },
    {
      name: 'PowerofEvil',
      nameAbb: 'Alphari',
      defSkill: 4,
      midSkill: 9,
      atkSkill: 3,
      teamless: true,
    },
  ],
};

const playerReducer = (state = initialState, action) => {
  switch (action.type) {
    default:
      return state;
  }
};

export default playerReducer;
