import * as actionTypes from '../Constants';

const initialState = {
  Players: [
    {
      name: 'Cristiano Ronaldo',
      nameAbb: 'C. Ronaldo',
      defSkill: 4,
      midSkill: 7,
      atkSkill: 10,
      teamless: true,
    },
    {
      name: 'Richard Papillon',
      nameAbb: 'Shox',
      defSkill: 5,
      midSkill: 9,
      atkSkill: 7,
      teamless: true,
    },
    {
      name: 'Augustas Eidikis',
      nameAbb: 'A. Eidikis',
      defSkill: 3,
      midSkill: 8,
      atkSkill: 9,
      teamless: true,
    },
    {
      name: 'Luka Perković',
      nameAbb: 'Perkz',
      defSkill: 6,
      midSkill: 6,
      atkSkill: 8,
      teamless: true,
    },
    {
      name: 'Oleksandr Kostyliev',
      nameAbb: 'S1mple',
      defSkill: 5,
      midSkill: 5,
      atkSkill: 10,
      teamless: true,
    },
    {
      name: 'Ilya Zalutskiy',
      nameAbb: 'Perfecto',
      defSkill: 8,
      midSkill: 6,
      atkSkill: 4,
      teamless: true,
    },
    {
      name: 'Nikola Kovač',
      nameAbb: 'NiKo',
      defSkill: 5,
      midSkill: 7,
      atkSkill: 7,
      teamless: true,
    },
    {
      name: 'Ludvig Brolin',
      nameAbb: 'Brollan',
      defSkill: 2,
      midSkill: 6,
      atkSkill: 9,
      teamless: true,
    },
    {
      name: 'Henrik Hansen',
      nameAbb: 'Froggen',
      defSkill: 5,
      midSkill: 8,
      atkSkill: 5,
      teamless: true,
    },
    {
      name: 'Barney Morris',
      nameAbb: 'Alphari',
      defSkill: 4,
      midSkill: 9,
      atkSkill: 3,
      teamless: true,
    },
    {
      name: 'Robert Lewandowski',
      nameAbb: 'R. Lewandowski',
      defSkill: 2,
      midSkill: 7,
      atkSkill: 8,
      teamless: true,
    },
    {
      name: 'Francesco Totti',
      nameAbb: 'F. Totti',
      defSkill: 3,
      midSkill: 10,
      atkSkill: 5,
      teamless: true,
    },
    {
      name: 'Paolo Maldini',
      nameAbb: 'P. Maldini',
      defSkill: 9,
      midSkill: 7,
      atkSkill: 2,
      teamless: true,
    },
    {
      name: 'Nemanja Vidić',
      nameAbb: 'N. Vidić',
      defSkill: 10,
      midSkill: 5,
      atkSkill: 1,
      teamless: true,
    },
    {
      name: 'Oskar Bogdan',
      nameAbb: 'Vander',
      defSkill: 8,
      midSkill: 3,
      atkSkill: 3,
      teamless: true,
    },
    {
      name: 'Andrei Pascu',
      nameAbb: 'Odoamne',
      defSkill: 6,
      midSkill: 6,
      atkSkill: 4,
      teamless: true,
    },
    {
      name: 'Rasmus Winther',
      nameAbb: 'CaPs',
      defSkill: 3,
      midSkill: 7,
      atkSkill: 9,
      teamless: true,
    },
    {
      name: 'Martin Larsson',
      nameAbb: 'Rekkles',
      defSkill: 3,
      midSkill: 4,
      atkSkill: 10,
      teamless: true,
    },
    {
      name: 'Marcin Jankowski',
      nameAbb: 'Jankos',
      defSkill: 8,
      midSkill: 8,
      atkSkill: 4,
      teamless: true,
    },
    {
      name: 'Elias Lipp',
      nameAbb: 'Upset',
      defSkill: 4,
      midSkill: 3,
      atkSkill: 7,
      teamless: true,
    },
    {
      name: 'Karim Benzema',
      nameAbb: 'K. Benzema',
      defSkill: 2,
      midSkill: 3,
      atkSkill: 10,
      teamless: true,
    },
    {
      name: 'Luka Modrić',
      nameAbb: 'L. Modrić',
      defSkill: 2,
      midSkill: 10,
      atkSkill: 7,
      teamless: true,
    },
    {
      name: 'Antoine Griezmann',
      nameAbb: 'A. Griezmann',
      defSkill: 3,
      midSkill: 4,
      atkSkill: 9,
      teamless: true,
    },
    {
      name: 'Thomas Müller',
      nameAbb: 'T. Müller',
      defSkill: 2,
      midSkill: 9,
      atkSkill: 7,
      teamless: true,
    },
    {
      name: 'Benjamin Pavard',
      nameAbb: 'B. Pavard',
      defSkill: 8,
      midSkill: 4,
      atkSkill: 4,
      teamless: true,
    },
    {
      name: 'Marcus Rashford',
      nameAbb: 'M. Rashford',
      defSkill: 2,
      midSkill: 5,
      atkSkill: 7,
      teamless: true,
    },
    {
      name: 'Erling Haaland',
      nameAbb: 'E. Haaland',
      defSkill: 2,
      midSkill: 3,
      atkSkill: 9,
      teamless: true,
    },
    {
      name: 'Giorgio Chiellini',
      nameAbb: 'G. Chiellini',
      defSkill: 10,
      midSkill: 6,
      atkSkill: 1,
      teamless: true,
    },
    {
      name: 'NGolo Kanté',
      nameAbb: 'N. Kanté',
      defSkill: 9,
      midSkill: 3,
      atkSkill: 3,
      teamless: true,
    },
    {
      name: 'Marius Grigonis',
      nameAbb: 'M. Grigonis',
      defSkill: 5,
      midSkill: 8,
      atkSkill: 5,
      teamless: true,
    },
    {
      name: 'Domantas Sabonis',
      nameAbb: 'D. Sabonis',
      defSkill: 2,
      midSkill: 3,
      atkSkill: 10,
      teamless: true,
    },
    {
      name: 'Romelu Lukaku',
      nameAbb: 'R. Lukaku',
      defSkill: 4,
      midSkill: 3,
      atkSkill: 7,
      teamless: true,
    },
    {
      name: 'Eden Hazard',
      nameAbb: 'E. Hazard',
      defSkill: 2,
      midSkill: 4,
      atkSkill: 10,
      teamless: true,
    },
    {
      name: 'Granit Xhaka',
      nameAbb: 'G. Xhaka',
      defSkill: 1,
      midSkill: 9,
      atkSkill: 5,
      teamless: true,
    },
    {
      name: 'Sergio Ramos',
      nameAbb: 'S. Ramos',
      defSkill: 7,
      midSkill: 5,
      atkSkill: 5,
      teamless: true,
    },
    {
      name: 'Harry Kane',
      nameAbb: 'H. Kane',
      defSkill: 2,
      midSkill: 4,
      atkSkill: 8,
      teamless: true,
    },
    {
      name: 'Kevin de Bruyne',
      nameAbb: 'K. de Bruyne',
      defSkill: 3,
      midSkill: 10,
      atkSkill: 7,
      teamless: true,
    },
    {
      name: 'Olof Kajbjer',
      nameAbb: 'Olofmeister',
      defSkill: 5,
      midSkill: 6,
      atkSkill: 7,
      teamless: true,
    },
    {
      name: 'Hampus Poser',
      nameAbb: 'Hampus',
      defSkill: 6,
      midSkill: 6,
      atkSkill: 5,
      teamless: true,
    },
    {
      name: 'Jonas Valančiūnas',
      nameAbb: 'J. Valančiūnas',
      defSkill: 10,
      midSkill: 3,
      atkSkill: 2,
      teamless: true,
    },
    {
      name: 'Robin van Persie',
      nameAbb: 'R. van Persie',
      defSkill: 2,
      midSkill: 5,
      atkSkill: 10,
      teamless: true,
    },
    {
      name: 'Vincent Kompany',
      nameAbb: 'V. Kompany',
      defSkill: 8,
      midSkill: 5,
      atkSkill: 2,
      teamless: true,
    },
    {
      name: 'Jorge Filho',
      nameAbb: 'Jorginho',
      defSkill: 3,
      midSkill: 9,
      atkSkill: 5,
      teamless: true,
    },
    {
      name: 'Kylian Mbappé',
      nameAbb: 'K. Mbappé',
      defSkill: 3,
      midSkill: 8,
      atkSkill: 8,
      teamless: true,
    },
    {
      name: 'Mathieu Herbaut',
      nameAbb: 'Zywoo',
      defSkill: 4,
      midSkill: 5,
      atkSkill: 10,
      teamless: true,
    },
    {
      name: 'Fredrico Chiesa',
      nameAbb: 'F. Chiesa',
      defSkill: 2,
      midSkill: 7,
      atkSkill: 7,
      teamless: true,
    },
    {
      name: 'Ciro Immobile',
      nameAbb: 'C. Immobile',
      defSkill: 4,
      midSkill: 7,
      atkSkill: 9,
      teamless: true,
    },
    {
      name: 'Kenny Schrub',
      nameAbb: 'KennyS',
      defSkill: 2,
      midSkill: 5,
      atkSkill: 10,
      teamless: true,
    },
    {
      name: 'Erberk Demir',
      nameAbb: 'Gilius',
      defSkill: 7,
      midSkill: 4,
      atkSkill: 3,
      teamless: true,
    },
    {
      name: 'Tristan Schrage',
      nameAbb: 'PowerOfEvil',
      defSkill: 3,
      midSkill: 6,
      atkSkill: 6,
      teamless: true,
    },
  ],
};

const playerReducer = (state = initialState, action) => {
  switch (action.type) {
    default:
      return state;
  }
};

export default playerReducer;
